name: EntityEditor
main: skh6075\entityeditor\EntityEditorLoader
author: AvasKr
version: 1.0.0
api: 3.10.0
website: https://github.com/GodVas

permissions:
  entity.editor.permission:
    default: op